apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: spring-boot-inflight-scaler
  namespace: default
spec:
  scaleTargetRef:
    name: spring-boot-app   # <-- Deployment name
  minReplicaCount: 1
  maxReplicaCount: 2
  cooldownPeriod: 30
  pollingInterval: 15
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://monitoring-prometheus-server.monitoring.svc.cluster.local
        metricName: inflight_requests
        threshold: "10"
        query: |
          sum(http_server_requests_active{job="spring-boot"})
