{{- if not .Values.postgres.secrets.sealed }}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: "grafana"
  POSTGRES_PASSWORD: "grafana"
  POSTGRES_DB: "grafana"
{{- end }}

