{{- if not .Values.grafana.oidc.secrets.sealed }}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-oidc-client-secret
type: Opaque
stringData:
  OAUTH_CLIENT_SECRET: "pBpGi5EgpXORPOx3oKEynuVZ361psZwm"
{{- end }}

