apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-external-secret
spec:
  refreshInterval: "1500s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: postgres-secret
    creationPolicy: Owner
  data:
    - secretKey: KC_BOOTSTRAP_ADMIN_USERNAME
      remoteRef:
        key: kv/keycloak
        property: KC_BOOTSTRAP_ADMIN_USERNAME
    - secretKey: KC_BOOTSTRAP_ADMIN_PASSWORD
      remoteRef:
        key: kv/keycloak
        property: KC_BOOTSTRAP_ADMIN_PASSWORD
    - secretKey: KC_DB_USERNAME
      remoteRef:
        key: kv/keycloak
        property: POSTGRES_USER
    - secretKey: KC_DB_PASSWORD
      remoteRef:
        key: kv/keycloak
        property: POSTGRES_PASSWORD