apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: b-cilium-gateway
spec:
  gatewayClassName: cilium
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: "*.192.168.100.242.sslip.io"
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.192.168.100.242.sslip.io"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: b-sslip-tls
            namespace: cilium
  addresses:
    - type: IPAddress
      value: 192.168.100.242
