apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: b-sslip-tls
  namespace: cilium
spec:
  secretName: b-sslip-tls
  dnsNames:
    - "*.192.168.100.244.sslip.io"
    - "192.168.100.244.sslip.io"
  issuerRef:
    name: vault-cluster-issuer
    kind: ClusterIssuer
