apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-metrics
  template:
    metadata:
      labels:
        app: admin-metrics
    spec:
      containers:
        - name: kubespheredev-prometheus-example-app
          image: docker.io/kubespheredev/prometheus-example-app:latest
          ports:
            - containerPort: 8080
