apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-metrics
  template:
    metadata:
      labels:
        app: admin-metrics
    spec:
      containers:
        - name: springboot-scalability
          image: docker.io/nikolahristovski/springboot-scalability:1.0.0
          ports:
            - containerPort: 8080
