apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-metrics
  template:
    metadata:
      labels:
        app: admin-metrics
    spec:
      containers:
        - name: brancz-prometheus-example-app
          image: quay.io/brancz/prometheus-example-app:0.5.0
          ports:
            - containerPort: 8080
