apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: docker.io/nginx:1.27-alpine
          env:
            - name: A
              value: "A"
          volumeMounts:
            - name: dv
              mountPath: /data
          ports:
            - containerPort: 80
      volumes:
        - name: dv
          persistentVolumeClaim:
            claimName: dv