secrets:
  sealed: false

grafana:

  adminPassword: NOT_USED

  securityContext:
    runAsNonRoot: true
    runAsUser: 472
    runAsGroup: 472
    fsGroup: 472

  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault
    readOnlyRootFilesystem: true

  extraEmptyDirMounts:
    - name: tmp
      mountPath: /tmp
    - name: plugins-temp
      mountPath: /var/lib/grafana/plugins
    - name: provisioning-temp
      mountPath: /etc/grafana/provisioning/notifiers

  readinessProbe:
    httpGet:
      path: /api/health
      port: 3000
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

  envFromSecret: grafana-secrets

  env:
    GF_SECURITY_ALLOW_EMBEDDING: true
    GF_CORS_ENABLED: true
    GF_CORS_ALLOW_CREDENTIALS: true
    GF_CORS_ALLOWED_ORIGINS: "https://grafana.192.168.100.243.sslip.io/,http://grafana.monitoring.svc.cluster.local,https://grafana.monitoring.svc.cluster.local"
    GF_CORS_ALLOWED_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
    GF_CORS_ALLOWED_HEADERS: "accept,authorization,content-type,origin"

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://monitoring-prometheus-server.monitoring.svc.cluster.local
          access: proxy
          isDefault: true
        - name: loki-platform
          access: proxy
          type: loki
          url: http://monitoring-loki.monitoring.svc.cluster.local:3100
          jsonData:
            httpHeaderName1: 'X-Scope-OrgID'
          secureJsonData:
            httpHeaderValue1: 'platform'
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: "default"
          orgId: 1
          folder: ""
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      kubernetes:
        gnetId: 10000
        revision: 1
        datasource: Prometheus
  grafana.ini:
    database:
      type: postgres
      host: grafana-postgres.monitoring.svc.cluster.local:5432
      name: ${POSTGRES_DB}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      ssl_mode: disable
    server:
      domain: https://grafana.192.168.100.243.sslip.io/
      root_url: https://grafana.192.168.100.243.sslip.io/
    auth.generic_oauth:
      enabled: true
      name: KEYCLOAK
      allow_sign_up: true
      client_id: grafana
      client_secret: ${OAUTH_CLIENT_SECRET}
      scopes: openid email profile offline_access roles
      email_attribute_path: email
      login_attribute_path: username
      name_attribute_path: full_name
      auth_url: https://keycloak.192.168.100.243.sslip.io/realms/grafana/protocol/openid-connect/auth
      token_url: http://keycloak.keycloak.svc.cluster.local:80/realms/grafana/protocol/openid-connect/token
      api_url: http://keycloak.keycloak.svc.cluster.local:80/realms/grafana/protocol/openid-connect/userinfo
      signout_redirect_url: https://keycloak.192.168.100.243.sslip.io/realms/grafana/protocol/openid-connect/logout
      role_attribute_path: contains(realm_access.roles[*], 'GrafanaSuperadmin') && 'GrafanaAdmin' || contains(realm_access.roles[*], 'GrafanaAdmin') && 'Admin' || contains(realm_access.roles[*], 'GrafanaEditor') && 'Editor' || 'Viewer'
      role_attribute_strict: true
      allow_assign_grafana_admin: true
    auth:
      disable_login_form: true
      oauth_auto_login: false
      oauth_skip_org_role_update_sync: false
      skip_org_role_sync: false
    users:
      auto_assign_org: true
      auto_assign_org_role: Viewer
      auto_assign_org_id: 1
    security:
      disable_initial_admin_creation: true
      disable_initial_admin_password_change: true
      allow_embedding: true
      cookie_secure: false
  ingress:
    enabled: false

  route:
    main:
      enabled: true

      hostnames:
        - grafana.192.168.100.243.sslip.io

      parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: default-cilium-gateway
          namespace: cilium
          sectionName: https

      matches:
        - path:
            type: PathPrefix
            value: /
  persistence:
    enabled: true
    storageClassName: ceph-block-storage
    size: 2Gi

loki:
  memcached:
    enabled: false
  memcachedExporter:
    enabled: false
  chunksCache:
    enabled: false
  resultsCache:
    enabled: false
  deploymentMode: SingleBinary
  gateway:
    enabled: false
  test:
    enabled: false
  lokiCanary:
    enabled: false
  loki:
    auth_enabled: true
    commonConfig:
      replication_factor: 1
    storage:
      type: "s3"
      bucketNames:
        chunks: loki-chunks
        ruler: loki-ruler
        admin: loki-admin
      s3:
        endpoint: http://192.168.100.226:80
        region: us-east-1
        secretAccessKey: loki-secret-key
        accessKeyId: loki-access-key
        s3ForcePathStyle: true
        insecure: true
    chunk_store_config:
      chunk_cache_config:
        embedded_cache:
          enabled: false
    limits_config:
      retention_period: 72h
      retention_stream:
        - selector: '{namespace=~".+"}'
          priority: 1
          period: 72h
    compactor:
      working_directory: /tmp/loki/compactor
      retention_enabled: true
      retention_delete_delay: 2h
      retention_delete_worker_count: 150
      delete_request_store: s3
    schemaConfig:
      configs:
        - from: 2024-04-01
          object_store: s3
          store: tsdb
          schema: v13
          index:
            prefix: index_
            period: 24h

    rulerConfig:
      storage:
        type: s3
        s3:
          bucketnames: loki-ruler

  singleBinary:
    replicas: 1
    extraEnvFrom:
      - secretRef:
          name: loki-s3-credentials
    extraVolumes:
      - name: loki-work-dir
        emptyDir: {}
    extraVolumeMounts:
      - name: loki-work-dir
        mountPath: /var/loki
    persistence:
      enabled: false
  write:
    replicas: 0
  read:
    replicas: 0
  backend:
    replicas: 0


prometheus:
  server:
    securityContext:
      runAsUser: 65534
      runAsNonRoot: true
      runAsGroup: 65534
      fsGroup: 65534
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
      readOnlyRootFilesystem: true
    persistentVolume:
      enabled: true
      storageClass: ceph-block-storage
      size: 5Gi
      existingClaim: prometheus-data-pvc
    extraFlags:
      - web.enable-remote-write-receiver
      - web.enable-lifecycle
    retention: "2d"

  prometheus-pushgateway:
    enabled: false
  prometheus-node-exporter:
    enabled: false
  kube-state-metrics:
    enabled: true
  alertmanager:
    enabled: false

alloy:
  alloy:
    clustering:
      enabled: false
    configMap:
      create: false
      name: monitoring-alloy
      key: config.alloy
    extraEnv:
      - name: HOSTNAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
    mounts:
      varlog: true
  controller:
    type: "daemonset"


