apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: scalability
spec:
  scaleTargetRef:
    name: scalability
  minReplicaCount: 1
  maxReplicaCount: 3
  cooldownPeriod: 30
  pollingInterval: 15
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://monitoring-prometheus-server.monitoring.svc.cluster.local
        metricName: custom
        threshold: "100"
        query: |
          sum(rate(http_server_requests_active_seconds_sum{job="scalability"}[1m]))
