apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bucket-app-data-credentials
spec:
  refreshInterval: "7500s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: bucket-app-data-credentials
    creationPolicy: Owner
  data:
    - secretKey: ACCESS_KEY_SECRET
      remoteRef:
        key: kv/bucket-app-data-credentials
        property: ACCESS_KEY_SECRET
