apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: secret-from-public-url
spec:
  refreshInterval: "7500s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: secret-from-public-url
    creationPolicy: Owner
  data:
    - secretKey: PASS
      remoteRef:
        key: kv/secret-from-public-url
        property: PASS
