apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: valkey-first-valkey-password
spec:
  refreshInterval: "7500s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: fist-val-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: kv/valkey-first-valkey-password
        property: password
