apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vault-root-key
spec:
  encryptedData:
    token: AgB8tz2U1rMJ79bIsbFDc1F8/leyHYXeOIzjpqMEljzX/Iv/EgkE6wv0Ld09V5hjv26UH4AssJ58U/Thj8llRy0Lz8tqPJbN8KWfhl8hWddsaEaA05SgYJBai0eTXhRUbVRQscazQqBYnRF9hL9wQA2TJuhKco1Xc0PXndZmV4GVo/IsEzq+oEroHcTuYj2wzVRqufu6nws3pxL+lkp45s+gGn/+REp5fl8SnwlMG2tNhTPb98/sUsQo0kdBjhXBz6FZq6x6Z+5zpd2/mrN3iO+9DkQOqPl715cWAOm3L1tmp/w5DOi05vbAB6NS3zKaSACUFlC4dc5QwoNDi+vpJjxQvZiD7DdXol7tXwGQEfg5rz4DK106jVQE5/NtDhaY+dSBSz9gX+wD7EuRNEJOa3+NezJNueZgPJoKbEp0xPkXcF32uo2i1PInSYw4gAwEQ70wyyelOLeafonKTWKrc0VgPS4zToRw0809b7hPMwFcVEjWoczGmPlmyTaspruqAAcg3Tp2inLlbZ6knDSj9lF835K3OXJ919gD7Piemin6MfOA9DxmU/MjF4/+lbKe99LyDe4G7L7QkXROwvV1NSKkk6n0PyaGDsbotbDqxdBO+DQ02VtSerBYXXJeU+xV/QlQ8KfUv/5XQHT/nftpoD/0YNcOGokkUevsDrJLXfYdAtXmHlKC1U95cXOR+z08DI4pzekTDQqiq86QPoqTzpLnk3DOB2O8UNT9YNk/
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      name: vault-root-key
    type: Opaque
{{/* ! MAKE SURE TO USE 'echo -n root-key | base64 '*/}}