apiVersion: v1
data:
  key1: RDhhTERvbjAzUndFNWJsNG1yTytJd1JaK0ZlQW1seFNTRzVnd3M5U2dKUkc=
  key2: RlM5U01hL2VycjZNM0ZIYTA1TEw0SHJRQ2pPOFQvSDVpZGhJVlB3REdxMzM=
  key3: RnRsYzR2cmdkeHJJbU9KTTh6c3RFTGE3S3dXa1JXTHI5c2lXcFJRT2hHWmw=
kind: Secret
metadata:
  name: vault-unseal-keys