apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: t
spec:
  refreshInterval: "7500s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: t
    creationPolicy: Owner
  data:
    - secretKey: t
      remoteRef:
        key: kv/t
        property: tt
