# mariadb configuration
mariadb-operator:
  fullnameOverride: "mariadb-operator"

  podSecurityContext:
    runAsUser: 1000
    fsGroup: 1000

  securityContext:
    allowPrivilegeEscalation: false
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000

  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      memory: 200Mi

  webhook:

    podSecurityContext:
      runAsUser: 1000
      fsGroup: 1000

    securityContext:
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000

    resources:
      requests:
        cpu: 1m
        memory: 20Mi
      limits:
        memory: 80Mi

  certController:

    podSecurityContext:
      runAsUser: 1000
      fsGroup: 1000

    securityContext:
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000

    resources:
      requests:
        cpu: 1m
        memory: 50Mi
      limits:
        memory: 80Mi