apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block-storage
  resources:
    requests:
      storage: 5Gi

