apiVersion: monitoring.grafana.com/v1alpha2
kind: PodLogs
metadata:
  name: admin-nginx
spec:
  selector:
    matchLabels:
      app: admin-nginx
  relabelings:
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
    - sourceLabels: [__meta_kubernetes_pod_container_name]
      targetLabel: container
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: node
