apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-external-secret
spec:
  refreshInterval: "1500s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: postgres-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_DB
      remoteRef:
        key: kv/keycloak
        property: POSTGRES_DB
    - secretKey: POSTGRES_USER
      remoteRef:
        key: kv/keycloak
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: kv/keycloak
        property: POSTGRES_PASSWORD