{{- if not .Values.secrets.sealed }}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
type: Opaque
stringData:
  OAUTH_CLIENT_SECRET: "pBpGi5EgpXORPOx3oKEynuVZ361psZwm"
  POSTGRES_USER: "grafana"
  POSTGRES_PASSWORD: "grafana"
  POSTGRES_DB: "grafana"
{{- end }}

