apiVersion: apps/v1
kind: Deployment
metadata:
  name: a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: a
  template:
    metadata:
      labels:
        app: a
    spec:
      containers:
        - name: a
          image: docker.io/a:a
          env:
            - name: AAA
              valueFrom:
                secretKeyRef:
                  name: A
                  key: A
            - name: BBB
              value: "BBB"
          volumeMounts:
          ports:
            - containerPort: 80
      volumes:
