apiVersion: apps/v1
kind: Deployment
metadata:
  name: a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: a
  template:
    metadata:
      labels:
        app: a
    spec:
      containers:
        - name: a
          image: docker.io/a:a
          env:
            - name: B
              value: "B"
            - name: A
              valueFrom:
                secretKeyRef:
                  name: A
                  key: A          volumeMounts:            - name: b              mountPath: /data      volumes:
        - name: b
          persistentVolumeClaim:
            claimName: b