apiVersion: apps/v1
kind: Deployment
metadata:
  name: a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: a
  template:
    metadata:
      labels:
        app: a
    spec:
      containers:
        - name: a
          image: a/a:a
          ports:
            - containerPort: 80
          env:
            - name: BB
              valueFrom:
                secretKeyRef:
                  name: b
                  key: b
            - name: AA
              valueFrom:
                secretKeyRef:
                  name: a
                  key: a
