apiVersion: apps/v1
kind: Deployment
metadata:
  name: b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: b
  template:
    metadata:
      labels:
        app: b
    spec:
      containers:
        - name: b
          image: b/b:b
          ports:
            - containerPort: 80
          env:
            - name: AA
              valueFrom:
                secretKeyRef:
                  name: a
                  key: a
