apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: nginx
          image: docker.io/nginx:1.27-alpine
          volumeMounts:
            - name: data2
              mountPath: data2
          ports:
            - containerPort: 80
      volumes:
        - name: data2
          persistentVolumeClaim:
            claimName: data2
