apiVersion: apps/v1
kind: Deployment
metadata:
  name: b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: b
  template:
    metadata:
      labels:
        app: b
    spec:
      containers:
        - name: b
          image: b/b:b
          env:
            - name: D
              value: "D"
            - name: C
              value: "C"