secrets:
  sealed: false

keycloak:
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
  production: true
  proxy: edge
  auth:
    adminUser: admin
    existingSecret: keycloak-secrets
    passwordSecretKey: adminPassword
  service:
    type: ClusterIP
  ingress:
    enabled: false
  externalDatabase:
    host: postgres.keycloak.svc.cluster.local
    database: keycloak
    port: 5432
    existingSecret: "postgres-keycloak-secret"
    existingSecretUserKey: "postgresUsername"
    existingSecretPasswordKey: "postgresPassword"
  postgresql:
    enabled: false
  extraEnvVars:
    - name: KC_HOSTNAME_URL
      value: https://keycloak.192.168.100.243.sslip.io
    - name: KC_HOSTNAME_ADMIN_URL
      value: https://keycloak.192.168.100.243.sslip.io
    - name: KC_PROXY_HEADERS
      value: "X-FORWARDED"