apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: catalog-external-secret
spec:
  refreshInterval: "1500s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: catalog-secret
    creationPolicy: Owner
  data:
    - secretKey: GIT_PASSWORD
      remoteRef:
        key: kv/platformcatalog
        property: GIT_PASSWORD
    - secretKey: OAUTH_CLIENT_SECRET
      remoteRef:
        key: kv/platformcatalog
        property: OAUTH_CLIENT_SECRET
    - secretKey: VAULT_TOKEN
      remoteRef:
        key: kv/platformcatalog
        property: VAULT_TOKEN