apiVersion: apps/v1
kind: Deployment
metadata:
  name: ww
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ww
  template:
    metadata:
      labels:
        app: ww
    spec:
      containers:
        - name: nginx
          image: docker.io/nginx:1.27-alpine
          env:
            - name: AAAAA
              valueFrom:
                secretKeyRef:
                  name: db
                  key: WW
            - name: ENV
              valueFrom:
                secretKeyRef:
                  name: db
                  key: password
            - name: AA
              value: "A"



