secrets:
  sealed: false

keycloak:
  global:
    security:
      allowInsecureImages: true
  image:
    repository: keycloak/keycloak
    tag: 26.4.7
    digest: sha256:9409c59bdfb65dbffa20b11e6f18b8abb9281d480c7ca402f51ed3d5977e6007
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
  production: true
  proxyHeaders: forwarded
  proxy: edge
  auth:
    adminUser: admin
    existingSecret: keycloak-secrets
    passwordSecretKey: adminPassword
  service:
    type: ClusterIP
  ingress:
    enabled: false
  externalDatabase:
    host: postgres.keycloak.svc.cluster.local
    database: keycloak
    port: 5432
    existingSecret: keycloak-secrets
    existingSecretUserKey: postgresUsername
    existingSecretPasswordKey: postgresPassword
  postgresql:
    enabled: false
  extraEnvVars:
    - name: KC_HOSTNAME_URL
      value: https://keycloak.caplatform.dpdns.org
    - name: KC_HOSTNAME_ADMIN_URL
      value: https://keycloak.caplatform.dpdns.org
    - name: KC_PROXY_HEADERS
      value: "forwarded"
    - name: KC_PROXY
      value: edge
    - name: KC_HOSTNAME
      value: https://keycloak.caplatform.dpdns.org
    - name: KC_HOSTNAME_STRICT
      value: "false"
    - name: KC_HTTP_ENABLED
      value: "true"
    - name: KC_HOSTNAME_STRICT_HTTPS
      value: "false"