apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: image
          image: docker.io/nginx:1.27-alpine
          volumeMounts:
            - name: data
              mountPath: /var/data
          ports:
            - containerPort: 80

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: username-data
