apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: nginx
          image: docker.io/nginx:1.27-alpine
          volumeMounts:
            - name: s2
              mountPath: /data2
            - name: s1
              mountPath: /data1
          env:
            - name: TEST2
              value: "test2"
            - name: TEST1
              value: "one"
          ports:
            - containerPort: 80




      volumes:
        - name: s2
          persistentVolumeClaim:
            claimName: s2
        - name: s1
          persistentVolumeClaim:
            claimName: s1

