apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: image
          image: docker.io/ngin:1.27-alpine
          env:
            - name: DB_HOST
              value: "test"
          volumeMounts:
            - name: s1
              mountPath: /data
          ports:
            - containerPort: 80







      volumes:
        - name: s1
          persistentVolumeClaim:
            claimName: username-s1

