apiVersion: v1
kind: Service
metadata:
  name: api-function
  labels:
    app: api-function
spec:
  selector:
    app: api-function
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
