keda-add-ons-http:
  interceptor:
    replicas:
      min: 2
      max: 3
      waitTimeout: 120s
    tcpConnectTimeout: 120s
    keepAlive: 120s
    idleConnTimeout: 120s
    tlsHandshakeTimeout: 120s
    responseHeaderTimeout: 120s
    expectContinueTimeout: 120s
