keda-add-ons-http:
  interceptor:
    replicas:
      min: 2
      max: 3
      waitTimeout: 15s
    tcpConnectTimeout: 15s
    keepAlive: 15s
    idleConnTimeout: 15s
    tlsHandshakeTimeout: 15s
    responseHeaderTimeout: 15s
    expectContinueTimeout: 15s
