keda-add-ons-http:
  interceptor:
    replicas:
      min: 2
      max: 3
      waitTimeout: 10s
    tcpConnectTimeout: 10s
    keepAlive: 10s
    idleConnTimeout: 10s
    tlsHandshakeTimeout: 10s
    responseHeaderTimeout: 10s
    expectContinueTimeout: 10s
