vault:
  fullnameOverride: vault

  injector:
    enabled: false

  server:
    dataStorage:
      size: 2Gi
      storageClass: ceph-block-storage

  ui:
    enabled: true

external-secrets:
  fullnameOverride: external-secrets

sealed-secrets:
  fullnameOverride: sealed-secrets