vault:
  fullnameOverride: vault

  injector:
    enabled: false

  server:
    dataStorage:
      size: 2Gi
      storageClass: ceph-block-storage

  ui:
    enabled: true

external-secrets:
  fullnameOverride: external-secrets
  crds:
    annotations:
      argocd.argoproj.io/sync-options: ServerSideApply=true

sealed-secrets:
  fullnameOverride: sealed-secrets


cert-manager:
  fullnameOverride: cert-manager
  crds:
    enabled: true
  config:
    apiVersion: "controller.config.cert-manager.io/v1alpha1"
    kind: "ControllerConfiguration"
    enableGatewayAPI: true