apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: second-secret
spec:
  refreshInterval: "7500s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: second-secret
    creationPolicy: Owner
  data:
    - secretKey: secretvalue
      remoteRef:
        key: kv/second-secret
        property: secretvalue
