apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: b
spec:
  refreshInterval: "7500s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: b
    creationPolicy: Owner
  data:
    - secretKey: b
      remoteRef:
        key: kv/b
        property: b
