apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: a
spec:
  refreshInterval: "7500s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: a
    creationPolicy: Owner
  data:
    - secretKey: a
      remoteRef:
        key: kv/a
        property: a
