apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: B
spec:
  refreshInterval: "7500s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: B
    creationPolicy: Owner
  data:
    - secretKey: B
      remoteRef:
        key: kv/B
        property: B
