apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-secret
spec:
  refreshInterval: "7500s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: keycloak-secret
    creationPolicy: Owner
  data:
    - secretKey: realm_secret
      remoteRef:
        key: kv/keycloak-secret
        property: realm_secret
