apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: A
spec:
  refreshInterval: "7500s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: A
    creationPolicy: Owner
  data:
    - secretKey: A
      remoteRef:
        key: kv/A
        property: A
