apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: nikolahristovski-springboot-scalability
          image: docker.io/nikolahristovski/springboot-scalability:1.0.0
          ports:
            - containerPort: 8080
