apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-extensions
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://github.com/NHristovski/masters-degree-thesis-argocd-app.git
      path: deployments/argocd-extensions
      targetRevision: main
