apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ceph
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ceph
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://github.com/NHristovski/masters-degree-thesis-argocd-app.git
      path: deployments/ceph
      targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
