apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  sources:
    - repoURL: https://github.com/NHristovski/masters-degree-thesis-argocd-app.git
      path: deployments/keycloak
      targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
