apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scalability
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: scalability
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://github.com/NHristovski/masters-degree-thesis-argocd-app.git
      path: platform-charts/scalability
      targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true