apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: secrets
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://github.com/NHristovski/masters-degree-thesis-argocd-app.git
      path: platform-charts/secrets
      targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: vault-vault-injector
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle