apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: username-p1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: p1
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://github.com/NHristovski/masters-degree-thesis-argocd-app.git
      path: platform-charts/username-p1
      targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
