apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: valkey-operator
  namespace: argocd
spec:
  project: default

  source:
    path: .
    repoURL: oci://ghcr.io/hyperspike/valkey-operator
    targetRevision: "v0.0.61-chart"
    helm:
      valuesObject:
        config:
          exporterImage: ghcr.io/hyperspike/valkey-sidecar:v0.0.51
          nodes: "1"
          valkeyImage: ghcr.io/hyperspike/valkey:8.1.4
        controllerManager:
          manager:
            args:
              - --leader-elect=false
              - --health-probe-bind-address=:8081
            containerSecurityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
            image:
              repository: ghcr.io/hyperspike/valkey-operator
              tag: v0.0.61
            resources:
              limits:
                cpu: 500m
                memory: 128Mi
              requests:
                cpu: 10m
                memory: 64Mi
          podSecurityContext:
            runAsNonRoot: true
          replicas: 1
          serviceAccount:
            annotations: {}
        kubernetesClusterDomain: cluster.local

  destination:
    server: https://kubernetes.default.svc
    namespace: valkey-operator-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true