{{ if .Values.secrets.sealed }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: ceph-block-storage-auth
  namespace: ceph-block-storage
spec:
  encryptedData:
    userID: AgAzK1zuabIW1FpLCPtR+ZHNFS/Z2zJe0REaT2opKfoGV8Px1PYiE3LjXtKnDyVzPMzWKOquOKtkbA5biRz2CNlLXYtIqgGcf+4M3IYqpWQlpVEahcPYrHu/KYNtxO+L4dTZzwho6M8A8TRg2kE0mZ9OJVWAlFllVS4SKuZB5ItILKQEVQ4unE3D4/+Kx3LEzvOKXWDQ+4QMtTTPBPA0waPMdvjQY85Mdcgy6XyfNjE/S/VUMe3FSMC8qRX6K1zNHudcm1OhdTzV7gUDgY9+zmNSKs8LjmFjf8feyiCOAqV/d0ka7v44qKK46yK76mLRLAJkYL50yW9l2goiXTlaL7G/prF+DpXaLHJmWz/KZikRSACuAs2wBNFY1NLBqQizpvCHZh92E1zHRp1RIls8ga6d6yLz185k7RP49TBfvygagJSbBc2L6FXUyd1JEsgHN8otUXNeUrAlZyIDEHSlQHO2CGvZqRFb4iwt/vHnA4qIQp4wuojnmv8qmTEobjXynpfB70kU9zBiAL6mPwaZHDBxhthHhCVrvDOGtqUltNNf3xZAmXqVaeTM5B+VHEOmjiZ8fgxQeIw+Wd/N3PrKYm0cDuVWlOaatTJKpM1GvYFxJEWJJBp5XChHnYlDMN6Uw2bYSKBjHmxiMKAyOd4mfnOn+bGLO5ehUkm1HP/7YWM9JAIGLyLcb6JpcRRalvGbMBy1DK9t
    userKey: AgAlPG480eRcIx5ftGri9vXwxK8nCPPLX6IC8krFVuH4V6AX+5bASnpkTg1MnSF49gBAbZjlzqz1SCFpSmLs4EIrN+JSwNKgZZjmO2wHufbpOwQ+95nQoG6Q5RWKGYbVTOo+/WGGvk7ytVkWRJ2noN4JCQfS/8jSvUXEqWWJ0X8+B+kbB+0WYu3AgonGQnfJH5oLklW0qb/F7NrAXxslTY6x7fz4+CUz7CuXZcfnnqqtjlSDWGm15u3pr/4Kn8vKTT1GiiR8vJUtbpcV+ZbvhOHV1fzrtmaDJch+kiOkc1Kiz0eeGUE8sDBt3nDQOOZjKSuKlRw6MvATXGJaJsV6i04BX2wu7KUrkFJ/kzbtkfX6Spgv6N2Z6gM7pO31eLU3IGuBKm12XCxa7wKsc4XJLSorjUa6S7bqgutnr2xLISlX9dsJYdFpmEsx28sFHVshY79smr48nofVPpmREpAiaBnBsg5EpfAmzJVukfjefHuuj7ro8I2cRF9deGSt1Mam9+uh3NJmUp73K+B6f8OGXKaIC+TgTnsdVVH1nlijv3xXMn+qCBnPBQ4+W3bbdVzXi9sFCogwRnuIT7KBWqiOh2pdHsHy4F8vHXIqKEwlH0k/Cb5I+gIZG3kBDk1YqIj84bqXt4i6PqGcrvT8rNkrY512lD+ON2IB8/IZzNZ2WZyuHjIJuiKeKqbQG7tv7u5t5UNxxjJjCCapUzSXMF6F0iirAZEvb1AAy7H40DwtgTatvyP3EFf3RMYW
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: ceph-block-storage-auth
      namespace: ceph-block-storage
{{- end }}