apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: test
spec:
  mariaDbRef:
    namespace: mariadb
    name: mariadb
    waitForIt: false
  privileges:
    - "ALL"
  database: test
  table: "*"
  username: test
  grantOption: false
  host: "%"
  requeueInterval: 30s
  retryInterval: 5s