apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: test
spec:
  mariaDbRef:
    namespace: mariadb
    name: mariadb
    waitForIt: false
  passwordSecretKeyRef:
    name: mariadb-pw
    key: DATABASE_PASSWORD
  maxUserConnections: 200
  host: "%"
  requeueInterval: 30s
  retryInterval: 5s