apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: docker.io/nginx:1.27-alpine
          ports:
            - containerPort: 80
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-appdb-password
                  key: DATABASE_PASSWORD
            - name: VALKEY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: valkey-my-cache-password
                  key: password
