apiVersion: v1
kind: Secret
metadata:
  name: ceph-admin
type: kubernetes.io/rbd
data:
  userID: azhzLXVzZXI=
  userKey: QVFDNlRiSm80N0IzSnhBQTBZMWJHeER4dWFvSDg1WmZZZmtmRFE9PQ==
  adminID: azhzLXVzZXI=
  adminKey: QVFDNlRiSm80N0IzSnhBQTBZMWJHeER4dWFvSDg1WmZZZmtmRFE9PQ==