apiVersion: v1
kind: Secret
metadata:
  name: ceph-file-storage-auth
stringData:
  {{/* VERY IMPORTANT: THE USER ID MUST BE WITHOUT client. */}}
  userID: kubefs
  userKey: AQD0B1BpeLW7JBAAuOFx6OlMaM4et107u7X2LQ==
