{{- if not .Values.secrets.sealed }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
stringData:
  postgresUsername: keycloak
  postgresPassword: kEycloak$raNdom%9
  adminPassword: kEycloakAdmin$raNdom%9
{{- end }}