apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: docker.io/keycloak/keycloak@sha256:9409c59bdfb65dbffa20b11e6f18b8abb9281d480c7ca402f51ed3d5977e6007
          args:
            - start
          ports:
            - containerPort: 8080

          env:
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_HOSTNAME
              value: keycloak
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_PROXY
              value: edge
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_METRICS_ENABLED
              value: "true"
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              value: jdbc:postgresql://postgres.keycloak.svc.cluster.local:5432/keycloak
          envFrom:
            - secretRef:
                name: keycloak-secret
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 5

          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          volumeMounts:
            - name: keycloak-data
              mountPath: /opt/keycloak/data

      volumes:
        - name: keycloak-data
          persistentVolumeClaim:
            claimName: keycloak-pvc
