apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: default-cilium-gateway
spec:
  gatewayClassName: cilium
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: "*.192.168.100.243.sslip.io"
  addresses:
    - type: IPAddress
      value: 192.168.100.243