apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scalability
spec:
  selector:
    matchLabels:
      app: scalability
  endpoints:
    - targetPort: 8080
      path: /actuator/prometheus
      interval: 30s
