apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: appdb
spec:
  mariaDbRef:
    namespace: mariadb
    name: mariadb
    waitForIt: false
  privileges:
    - "ALL"
  database: appdb
  table: "*"
  username: appuser
  grantOption: false
  host: "%"
  requeueInterval: 30s
  retryInterval: 5s
